version: '3.8'
services:
  db:
    container_name: pg_container
    image: "postgres:13"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Pass1234
      POSTGRES_DB: helpschool
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    depends_on:
      - db
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8081:80"
volumes:
  db-data:
  pgadmin-data: